services:
    web-server:
        image: nginx:latest
        ports:
            - "80:80"
        volumes:
            - ./nginx/conf.d/default.conf:/etc/nginx/conf.d/default.conf
#            - ./app:/app
    app:
        build:
            dockerfile: ./php/Dockerfile
        volumes:
            - ./app:/app

